CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add new pair

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add new asset

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add qtum

CHANGELOG.md, rest-api.md, rest-api_JP.md
=> fix(rest-api): style

CHANGELOG.md, public-api.md, public-api_JP.md
publicに以下のエンドポイントを追加
- tickers
- tickers_jpy
=> feat: add tickers and tickers_jpy

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add xym

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add link

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add mkr

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: add boba

CHANGELOG.md, assets.md, pairs.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
* ENJ追加に伴う修正
* pair, assetを別マークダウンに切り出し
=> feat: add enj and refactoring

CHANGELOG.md, assets.md, pairs.md
=> feat: add matic

CHANGELOG.md, assets.md, pairs.md
=> feat: add dot and doge

CHANGELOG.md, public-stream.md, public-stream_JP.md
=> feat: Socket.IO version up

CHANGELOG.md, pairs.md, rest-api.md, rest-api_JP.md
* Termination of Crypto Pairs with BTC, excluding BTC/JPY
* https://blog.bitbank.cc/853258298/
=> feat: termination of crypto pairs with BTC (2022-09-15)

CHANGELOG.md, assets.md, pairs.md
=> feat: add astr

CHANGELOG.md, assets.md, pairs.md
=> feat: add ada

CHANGELOG.md, assets.md, pairs.md
=> feat: add avax

CHANGELOG.md, public-stream.md, public-stream_JP.md
自動切断廃止
auto disconnection is abolished
=> fix: auto disconnection abolished

CHANGELOG.md, assets.md, pairs.md
=> feat: add axs

CHANGELOG.md, assets.md, pairs.md
=> feat: add flr

CHANGELOG.md, assets.md, pairs.md
=> feat: add sand

CHANGELOG.md, rest-api.md, rest-api_JP.md
=> feat(rest-api): document about new deposit and withdrawal API

CHANGELOG.md, rest-api.md, rest-api_JP.md
=> BREAKING fix: withdrawal request also changed

CHANGELOG.md, rest-api.md, rest-api_JP.md
=> fix: deposit history response

CHANGELOG.md, assets.md, pairs.md
GALA、APE、CHZ追加に伴う修正
announcement: https://blog.bitbank.cc/684265328/
=> feat: add new coins gala / ape / chz

CHANGELOG.md, assets.md, pairs.md
OAS追加に伴う修正
announcement: https://blog.bitbank.cc/979692342/
=> feat: add new coin oas

public-api.md, public-api_JP.md
=> Fix typos in public API documents

CHANGELOG.md, rest-api.md, rest-api_JP.md
=> feat: add stopFlag on spot-pairs response

CHANGELOG.md, assets.md, pairs.md
MANA追加に伴う修正
announcement: https://blog.bitbank.cc/205363383/
=> feat: add new coin mana

CHANGELOG.md, public-api.md, public-api_JP.md, rest-api.md, rest-api_JP.md
=> fix: github issue

CHANGELOG.md, package-lock.json, package.json, rest-api.md, rest-api_JP.md
We now returns fully-filled/canceled orders only for 3 months ago. The download order history page is a new way to get older orders.
Also updates npm packages.
=> feat: only 3 months for get order(s)

CHANGELOG.md, assets.md, pairs.md
GRT追加に伴う修正
announcement: https://blog.bitbank.cc/191944150/
=> feat: add new coin grt

CHANGELOG.md, rest-api.md, rest-api_JP.md
issueへの対応
fix:
https://github.com/bitbankinc/bitbank-api-docs/issues/90
=> fix: parameters description in cancel_orders

CHANGELOG.md, assets.md, pairs.md
RNDR追加に伴う修正
announcement: https://blog.bitbank.cc/282688480/
=> feat: add new coin rndr

CHANGELOG.md, rest-api.md, rest-api_JP.md
タグ正規化のpublic docs更新です。
addressが GET /user/deposit_historyのResponseに追加されております。
=> feat: Update Public Docs (タグ正規化)

CHANGELOG.md, assets.md, errors.md, pairs.md, rest-api.md, rest-api_JP.md
BNB追加に伴う修正
announcement: https://blog.bitbank.cc/376756918/
=> feat: add new coin bnb

CHANGELOG.md, public-api.md, public-api_JP.md, public-stream.md, public-stream_JP.md, rest-api.md, rest-api_JP.md
=> feat: circuit break info

CHANGELOG.md, rest-api.md, rest-api_JP.md
Add a new endpoint: GET /user/margin/status
🌌
=> feat(rest-api): add /user/margin/status
